# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/mueller/SOCL3/pictrlzync/pictrlzync.srcs/sources_1/bd/zedb_sys/ip/zedb_sys_processing_system7_0_0/zedb_sys_processing_system7_0_0.xci
# IP: The module: 'zedb_sys_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/mueller/SOCL3/pictrlzync/pictrlzync.gen/sources_1/bd/zedb_sys/ip/zedb_sys_processing_system7_0_0/zedb_sys_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedb_sys_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/mueller/SOCL3/pictrlzync/pictrlzync.srcs/sources_1/bd/zedb_sys/ip/zedb_sys_processing_system7_0_0/zedb_sys_processing_system7_0_0.xci
# IP: The module: 'zedb_sys_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/mueller/SOCL3/pictrlzync/pictrlzync.gen/sources_1/bd/zedb_sys/ip/zedb_sys_processing_system7_0_0/zedb_sys_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedb_sys_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
