# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedbobp.xdc

# Block Designs: bd/zedpi_sys/zedpi_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedpi_sys || ORIG_REF_NAME==zedpi_sys} -quiet] -quiet

# IP: bd/zedpi_sys/ip/zedpi_sys_processing_system7_0_0/zedpi_sys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedpi_sys_processing_system7_0_0 || ORIG_REF_NAME==zedpi_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/zedpi_sys/ip/zedpi_sys_pictrlip_0_0/zedpi_sys_pictrlip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedpi_sys_pictrlip_0_0 || ORIG_REF_NAME==zedpi_sys_pictrlip_0_0} -quiet] -quiet

# IP: bd/zedpi_sys/ip/zedpi_sys_ps7_0_axi_periph_0/zedpi_sys_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedpi_sys_ps7_0_axi_periph_0 || ORIG_REF_NAME==zedpi_sys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zedpi_sys/ip/zedpi_sys_rst_ps7_0_100M_0/zedpi_sys_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedpi_sys_rst_ps7_0_100M_0 || ORIG_REF_NAME==zedpi_sys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zedpi_sys/ip/zedpi_sys_auto_pc_0/zedpi_sys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedpi_sys_auto_pc_0 || ORIG_REF_NAME==zedpi_sys_auto_pc_0} -quiet] -quiet

# XDC: c:/mueller/SOCL3/pic16hardware/pic16hardware.gen/sources_1/bd/zedpi_sys/zedpi_sys_ooc.xdc
