# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zedb_sys/zedb_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedb_sys || ORIG_REF_NAME==zedb_sys} -quiet] -quiet

# IP: bd/zedb_sys/ip/zedb_sys_processing_system7_0_0/zedb_sys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedb_sys_processing_system7_0_0 || ORIG_REF_NAME==zedb_sys_processing_system7_0_0} -quiet] -quiet

# XDC: c:/mueller/SOCL3/pictrlzync/pictrlzync.gen/sources_1/bd/zedb_sys/zedb_sys_ooc.xdc
