# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/SOC codes/new/pic16hardware/pic16hardware.srcs/sources_1/bd/zedpi_sys/ip/zedpi_sys_auto_pc_0/zedpi_sys_auto_pc_0.xci
# IP: The module: 'zedpi_sys_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SOC codes/new/pic16hardware/pic16hardware.gen/sources_1/bd/zedpi_sys/ip/zedpi_sys_auto_pc_0/zedpi_sys_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedpi_sys_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/SOC codes/new/pic16hardware/pic16hardware.srcs/sources_1/bd/zedpi_sys/ip/zedpi_sys_auto_pc_0/zedpi_sys_auto_pc_0.xci
# IP: The module: 'zedpi_sys_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/SOC codes/new/pic16hardware/pic16hardware.gen/sources_1/bd/zedpi_sys/ip/zedpi_sys_auto_pc_0/zedpi_sys_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedpi_sys_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
